language: java

matrix:
  include:
    - sudo: false
      jdk: oraclejdk8
    - sudo: required
      dist: precise
      jdk: oraclejdk8
    - sudo: required
      dist: trusty
      jdk: oraclejdk8

